[package]
name = "search"
version = "0.1.0"
authors = ["Andy Winston <andywinston@wi.rr.com>"]
edition = "2018"

[dependencies]
http = "0.1"
regex = "1.2.1"
json = "0.11.15"
dict = "0.1.5"

[dependencies.url]
git = "https://github.com/servo/rust-url"
 
